### ISSUE TITLE
Release 0.2 stable

### ISSUE THREAD

**Issue by dapplion** [aragon/buidler-aragon#77]
This issue summarizes the progress/status before v0.2.0 stable release

### Goals

- [x] Release v0.2.0 (Tentative date Wednesday)
- [x] Communicate the release to the community (Tentative date Friday)

#### Required items

- [x] Update react-boilerpalte to have the new publish task @0xGabi https://github.com/aragon/aragon-react-boilerplate/pull/105 (waiting to release)
- [x] Manually test new features @0xGabi 
- [x] Write comms for the 0.2.0 release @0xGabi ([First draft](https://docs.google.com/document/d/1rzvDEhs-F-0XoMBRaBMRSQ2SThj-8goWsMUIiOdUcDs/edit))
- [x] Support repos without an `app` dir #108 
- [x] Support publishing on different networks using a local key file and Frame @dapplion #99 
- [x] Sanity check IPFS API before doing a POST request on `uploadReleaseToIpfs` https://github.com/aragon/buidler-aragon/pull/101 @dapplion 
- [x] Review and decided to merge https://github.com/aragon/buidler-aragon/pull/82
- [x] ~Review and merge~ https://github.com/aragon/buidler-aragon/pull/91 (we decided not to modify the arfiact.json)
- [x] On publish, show URL with the API's own gateway instead of another gateway
- [x] Debug mnemonic file loading

#### Nice to have items
- [ ] Clean `start-task` code
- [ ] Support repos without smart contract code
- [ ] Support script hooks and dao creation on other netowrks  
- [ ] Improve deploy contract logic @dapplion 
- [ ] Move `chainId` hardcoded (5555) to an environment or constants file with a comment

---
#### Previous Goals

This issue summarizes the progress/status towards a 0.2 stable release

- [x] Fully functional publish command: must be able to release existing apps and community apps on localhost
- [x] Offer primitive support for running secondary apps with a front end in development

##### Required items
- [x] Review and merge #36 
- [x] Review and merge #79
- [x] Read IPFS ignore patterns from files (`.ipfsignore`) and do not expose an option #92 
- [x] In publish, default managerAddres to account[0] #90  
- [x] Review `environment`, `appName`, `appId` deprecation and requirements with #91
- [x] Send the publish tx by default with an option to configure it to be a dry run, printing the tx Data https://github.com/aragon/buidler-aragon/pull/90
- [x] In publish, it would be nice to have these three cases covered https://github.com/aragon/buidler-aragon/pull/89:
	- [x] Repo doesn't exist; deploys new contract and repo
	- [x] Repo exists, do a minor or patch with just content changing
	- [x] Repo exists, do a major with new contract and content

#### Out of scope
- Any new features on aragen / Snapshots
- Not using ganache server and using buidlerevm
- Interactive UI

**Comment by sohkai** [comment]
> Add a new flag (and maybe option) in publish to prevent app front-end build

Wondering what the use case of this would be? When you want to upgrade the contract but not the frontend?

**Comment by 0xGabi** [comment]
> Wondering what the use case of this would be? When you want to upgrade the contract but not the frontend?

I thought might be a useful way to prevent the buidling time during tests.

**Comment by sohkai** [comment]
> I thought might be a useful way to prevent the buidling time during tests.

By tests, do you mean running contract tests, or doing a dry test run of the publish command?

**Comment by 0xGabi** [comment]
The second, doing dry test run.

**Comment by 0xGabi** [comment]
I'll go ahead and close this one as we already address the required items. Will open a new issue to track the few tasks left before release 0.2.0

**Comment by 0xGabi** [comment]
We will track on this issue again so Lion have permissions to edit

**Comment by sohkai** [comment]
On

> Support repos without smart contract code

Would this just be for enabling publish in the client? Maybe we can say this is outside the responsibilities of this plugin (you're never going to be developing an Aragon App without a contract at the current moment).

**Comment by 0xGabi** [comment]
The use case that I thought was using the plugin to create a script hook without developing an Aragon app.

**Comment by 0xGabi** [comment]
Close with #129
